-- 
-- Database Create Script  
--
CREATE DATABASE IF NOT EXISTS openapps_OAE_D01;

USE openapps_OAE_D01;

/**
 *  ARCH TABLE
 */
CREATE TABLE ARCH_AGGREGATE
(
   AGGREGATE_ID int(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
   AGGREGATE_NAME varchar(255)
);
CREATE UNIQUE INDEX UQ_AGGREGATE_NAME ON ARCH_AGGREGATE(AGGREGATE_NAME);

CREATE TABLE ARCH_AGGREGATE_SERVICE
(
   AGGREGATE_ID INT(11) NOT NULL,
   SERVICE_NAME varchar(255) NOT NULL,
   SERVICE_RUNNER_CLASS varchar(100) NOT NULL,
   SERVICE_RUNNER_METHOD varchar(100) NOT NULL,
   REQUIRES_DELEGATOR char(1) NOT NULL,
   XML_SERVICE char(1) NOT NULL,
   INDEX FK_ARCH_AS_AGGREGATE_ID (AGGREGATE_ID),
   FOREIGN KEY (AGGREGATE_ID) REFERENCES ARCH_AGGREGATE(AGGREGATE_ID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX UQ_SERVICE_NAME ON ARCH_AGGREGATE_SERVICE(SERVICE_NAME);
CREATE UNIQUE INDEX UQ_SERVICE_RUNNER_CLASS ON ARCH_AGGREGATE_SERVICE(SERVICE_RUNNER_CLASS,SERVICE_RUNNER_METHOD);
----

/**
 *  SECURITY
 */
CREATE TABLE SEC_GROUP
(
   GROUP_ID INT(11) AUTO_INCREMENT PRIMARY KEY NOT NULL,
   GROUP_NAME VARCHAR(255)
);

CREATE TABLE SEC_APP_USER
(
   USERNAME VARCHAR(255) PRIMARY KEY NOT NULL,
   ENABLED BIT NOT NULL,
   PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE SEC_AUTHORITY
(
   AUTHORITY VARCHAR(255) PRIMARY KEY NOT NULL,
   USERNAME VARCHAR(255) NOT NULL
);

ALTER TABLE SEC_AUTHORITY
ADD CONSTRAINT FK_SEC_AUTH_USERNAME
FOREIGN KEY (USERNAME)
REFERENCES SEC_APP_USER(USERNAME);

CREATE UNIQUE INDEX UQ_SEC_AUTH_AUTH_USERNAME ON SEC_AUTHORITY(AUTHORITY,USERNAME);

CREATE TABLE SEC_GROUP_AUTHORITY
(
   AUTHORITY VARCHAR(255) PRIMARY KEY NOT NULL,
   GROUP_ID VARCHAR(255) NOT NULL
);

ALTER TABLE SEC_GROUP_AUTHORITY
ADD CONSTRAINT FK_GA_GROUP_ID
FOREIGN KEY (GROUP_ID)
REFERENCES SEC_GROUP(GROUP_ID);

ALTER TABLE SEC_GROUP_AUTHORITY
ADD CONSTRAINT FK_AUTH_AUTHORITY
FOREIGN KEY (AUTHORITY)
REFERENCES SEC_AUTHORITY(AUTHORITY);

DROP TABLE SEC_GROUP_USER;

CREATE TABLE SEC_GROUP_USER
(
   USERNAME VARCHAR(255),
   GROUP_ID INT(11)
);

ALTER TABLE SEC_GROUP_USER
ADD CONSTRAINT FK_GU_GROUP_ID
FOREIGN KEY (GROUP_ID)
REFERENCES SEC_GROUP(GROUP_ID);

ALTER TABLE SEC_GROUP_USER
ADD CONSTRAINT FK_GU_USERNAME
FOREIGN KEY (USERNAME)
REFERENCES SEC_APP_USER(USERNAME);

CREATE UNIQUE INDEX UQ_GU_UNQKEY ON SEC_GROUP_USER(USERNAME,GROUP_ID);
---

/**
 *  PARTY AGGREGATE TABLES
 */
--
-- PM_PARTY
-- 
CREATE TABLE `PM_PARTY`
(
   `PARTY_ID` int(11) NOT NULL AUTO_INCREMENT,
   `PARTY_TYPE` varchar(5) NOT NULL,
   `EXTERNAL_ID` varchar(20),
   `PREFERRED_CURRENCY_UOM` VARCHAR(5) NULL,
   `DESCRIPTION` longtext,
   `STATUS` varchar(5) NOT NULL,
   PRIMARY KEY (`PARTY_ID`)
);

/**
 *  ITEM_MASTER AGGREGATE TABLES
 */
--
-- IT_ITEM_MASTER
-- 
CREATE TABLE `IT_ITEM_MASTER` (
  `ITEM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `DESC` varchar(255) NOT NULL,
  `TYPE` varchar(5) NOT NULL,
  `UOM` varchar(5) NOT NULL,
  `STATUS` varchar(5) NOT NULL,
  `COST` decimal(18,2) DEFAULT '0.00',
  `PRICE` decimal(18,2) DEFAULT '0.00',
  `WEIGHT` decimal(18,2) DEFAULT '0.00',
  `CURCODE` varchar(5) NOT NULL,
  `SHIP_CHARGES` decimal(18,2) DEFAULT '0.00',
  `PERISHABLE` bit NOT NULL,
  `CAT01` varchar(15) NOT NULL,
  `CAT02` varchar(15) NOT NULL,
  `CAT03` varchar(15) NOT NULL,
  `CAT04` varchar(15) NOT NULL,
  `CAT05` varchar(15) NOT NULL,
  PRIMARY KEY (`ITEM_ID`)
);

/**
 *  SALES_ORDER AGGREGATE TABLES
 */
--
-- SO_SALES_HDR
-- 
CREATE TABLE `SO_SALES_HDR` (
  `SALES_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ORDTYPE` varchar(10) NOT NULL,
  `PARTY_ID` int(11) NOT NULL,
  `STATUS` varchar(5) NOT NULL,
  `TOT_QTY` decimal(18,2) DEFAULT '0.00',
  `TOT_AMT` decimal(18,2) DEFAULT '0.00',
  `TOT_TAX` decimal(18,2) DEFAULT '0.00',
  `TOT_WEIGHT` decimal(18,2) DEFAULT '0.00',
  `CUR_CODE` varchar(5) NOT NULL,
  `ORD_DATE` DATETIME NOT NULL,
  `SHIP_DATE` DATETIME NULL,
  `CAN_DATE` DATETIME NULL,
  `MODE_PAY` varchar(5) NOT NULL,
  `SHIP_TYPE` varchar(5) NOT NULL,
  `CARRIER` varchar(15) NOT NULL,
  `SHIP_CHARGES` decimal(18,2) NULL DEFAULT '0.00',
   PRIMARY KEY (`SALES_ID`)
);

ALTER TABLE SO_SALES_HDR
ADD CONSTRAINT SOSH_PARTY_ID
FOREIGN KEY (PARTY_ID)
REFERENCES PM_PARTY(PARTY_ID);

--
-- SO_SALES_DET
-- 
CREATE TABLE `SO_SALES_DET` (
  `SALES_ID` int(11) NOT NULL,
  `ORD_TYPE` varchar(10) NOT NULL,
  `LINE_NO` int(11) NOT NULL,
  `ITEM_ID` int(11) NOT NULL,
  `QTY_ORD` decimal(18,2) DEFAULT '0.00',
  `UOM` varchar(5) NOT NULL,
  `WEIGHT` decimal(18,2) DEFAULT '0.00',
  `LOCATION` varchar(255) NOT NULL,
  `LOT_NO` varchar(255) NOT NULL,
  `PRICE` decimal(18,2) DEFAULT '0.00',
  `COST` decimal(18,2) DEFAULT '0.00',
  `DISCOUNT` decimal(18,2) DEFAULT '0.00'
);

ALTER TABLE SO_SALES_DET
ADD CONSTRAINT SOSD_SALES_ID
FOREIGN KEY (SALES_ID)
REFERENCES SO_SALES_HDR(SALES_ID);

ALTER TABLE SO_SALES_DET
ADD CONSTRAINT SOSD_ITEM_ID
FOREIGN KEY (ITEM_ID)
REFERENCES IT_ITEM_MASTER(ITEM_ID);

CREATE UNIQUE INDEX SOSD_SALES_DET_UNQCD ON SO_SALES_DET(ITEM_ID,LINE_NO);