--
-- PARTY MANAGER
--
CREATE TABLE `PM_PARTY` (
  `PM_PARTY_ID` int(11) NOT NULL auto_increment,
  `PM_DESCRIPTION` longtext,
  `PM_EXTERNAL_ID` varchar(50) default NULL,
  `PM_PARTY_TYPE` varchar(100) NOT NULL,
  `PM_PREFERRED_CURRENCY_UOM` varchar(50) default NULL,
  `PM_STATUS` varchar(50) NOT NULL,
  PRIMARY KEY  (`PM_PARTY_ID`),
  INDEX (`PM_PERSON_ID`),
  UNIQUE KEY `PM_PARTY_ID` (`PM_PARTY_ID`)
);

CREATE TABLE `PM_PERSON` (
  `PM_PERSON_ID` int(11) NOT NULL,
  `PM_BIRTH_DATE` datetime default NULL,
  `PM_COMMENTS` longtext,
  `PM_DECEASED_DATE` datetime default NULL,
  `PM_FIRST_NAME` varchar(100) NOT NULL,
  `PM_GENDER` bit(1) NULL,
  `PM_LAST_NAME` varchar(100) NOT NULL,
  `PM_MARITAL_STATUS` varchar(10) default NULL,
  `PM_MIDDLE_NAME` varchar(100) default NULL,
  `PM_NICK_NAME` varchar(50) default NULL,
  `PM_PASSPORT_EXPIRATION_DATE` datetime default NULL,
  `PM_PASSPORT_NUMBER` varchar(50) default NULL,
  `PM_SALUTAION` varchar(100) NULL,
  `PM_SSN` varchar(50) default NULL,
  `PM_SUFFIX` varchar(50) default NULL,
  PRIMARY KEY  (`PM_PERSON_ID`),
  INDEX (`PM_PERSON_ID`),
  FOREIGN KEY (`PM_PERSON_ID`) REFERENCES PM_PARTY (`PM_PARTY_ID`)
);

CREATE TABLE `PM_PARTY_CONTACT_MECH` (
  `CM_CONTACT_MECH_ID` int(11) NOT NULL auto_increment,
  `CM_CONTACT_MECH_PURPOSE` varchar(50) NOT NULL,
  `CM_CONTACT_MECH_TYPE` varchar(50) NOT NULL,
  `CM_INFO_STRING` varchar(100) NOT NULL,
  `CM_PARTY_ID` int(11) NOT NULL,
  PRIMARY KEY  (`CM_CONTACT_MECH_ID`),
  FOREIGN KEY `FK_PARTY_ID` (`CM_PARTY_ID`) REFERENCES `PM_PARTY`(`PM_PARTY_ID`)
);

CREATE TABLE `AB_ADDRESS_BOOK` (
  `AB_ADDRESS_BOOK_ID` int(11) NOT NULL auto_increment,
  `AB_ADDRESS_1` varchar(100) NOT NULL,
  `AB_ADDRESS_2` varchar(100) default NULL,
  `AB_ATTN_NAME` varchar(100) NOT NULL,
  `AB_CITY` varchar(100) NOT NULL,
  `AB_COUNTRY` varchar(100) NOT NULL,
  `AB_DIRECTIONS` varchar(100) default NULL,
  `AB_POSTAL_CODE` varchar(100) NOT NULL,
  `AB_POSTAL_CODE_EXT` varchar(100) default NULL,
  `AB_STATE_PROVINCE` varchar(100) NOT NULL,
  `AB_TO_NAME` varchar(100) NOT NULL,
  PRIMARY KEY  (`AB_ADDRESS_BOOK_ID`)
);

CREATE TABLE `PARTY_ADDRESS` (
  `PM_PARTY_ID` int(11) NOT NULL,
  `AB_ADDRESS_ID` int(11) NOT NULL,
  PRIMARY KEY  (`PM_PARTY_ID`,`AB_ADDRESS_ID`),
  UNIQUE KEY `PM_PARTY_ID` (`PM_PARTY_ID`),
  UNIQUE KEY `AB_ADDRESS_ID` (`AB_ADDRESS_ID`),
  FOREIGN KEY `FK_ADDRESS_ID` (`AB_ADDRESS_ID`) REFERENCES `AB_ADDRESS_BOOK` (`AB_ADDRESS_ID`),
  FOREIGN KEY `FK_PARTY_ID` (`PM_PARTY_ID`) REFERENCES `PM_PARTY` (`PM_PARTY_ID`)
);

CREATE TABLE `AB_ROLE` (
  `AB_ADDRESS_ROLE_ID` int(11) NOT NULL,
  `AB_ROLE_VALUE` varchar(100) NOT NULL,
  `AB_ROLE_FROM_DATE` datetime NOT NULL,
  `AB_ROLE_TO_DATE` datetime NOT NULL,
  PRIMARY KEY  (`AB_ADDRESS_ROLE_ID`),
  INDEX(`AB_ADDRESS_ROLE_ID`)
);

CREATE TABLE `AB_ADDRESS_ROLE` (
  `AR_ADDRESS_ROLE_ID` int(11) NOT NULL,
  `AR_ADDRESS_BOOK_ID` int(11) NOT NULL,
  PRIMARY KEY  (`AR_ADDRESS_ROLE_ID`,`AR_ADDRESS_BOOK_ID`),
  INDEX(`AR_ADDRESS_BOOK_ID`),
  FOREIGN KEY `FK_AR_ADDRESS_ROLE_ID` (`AR_ADDRESS_ROLE_ID`) REFERENCES AB_ROLE(`AB_ADDRESS_ROLE_ID`),
  FOREIGN KEY `FK_AR_ADDRESS_BOOK_ID` (`AR_ADDRESS_BOOK_ID`) REFERENCES AB_ADDRESS_BOOK(`AB_ADDRESS_ID`)
);
