//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.29 at 07:22:13 AM IST 
//


package com.openappengine.itemmaster.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.ms.openapps.messages.BaseRequestMessage;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ItemMaster" type="{http://openappengine.com/itemmaster/types}ItemMaster"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "itemMaster"
})
@XmlRootElement(name = "CreateItemMasterRequest")
public class CreateItemMasterRequest extends BaseRequestMessage {
	private static final long serialVersionUID = 1L;
	
	@XmlElement(name = "ItemMaster", required = true)
    protected ItemMaster itemMaster;

    /**
     * Gets the value of the itemMaster property.
     * 
     * @return
     *     possible object is
     *     {@link ItemMaster }
     *     
     */
    public ItemMaster getItemMaster() {
        return itemMaster;
    }

    /**
     * Sets the value of the itemMaster property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemMaster }
     *     
     */
    public void setItemMaster(ItemMaster value) {
        this.itemMaster = value;
    }

}
