<?xml version="1.0" encoding="UTF-8"?>
<definitions 
	name="Party" 
	targetNamespace="http://openappengine.com/party"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:tns="http://openappengine.com/party"
	xmlns:party="http://openappengine.com/party/types"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
	<types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://openappengine.com/party/types"
				schemaLocation="party.xsd" />
		</xsd:schema>
	</types>

	<message name="CreatePartyRequestMessage">
		<part name="body" element="party:CreatePartyRequest" />
	</message>
	<message name="CreatePartyResponseMessage">
		<part name="body" element="party:CreatePartyResponse" />
	</message>
 	
	
	<portType name="PartyPortType">

		<operation name="CreateParty">
			<input message="tns:CreatePartyRequestMessage" />
			<output message="tns:CreatePartyResponseMessage" />
		</operation>

	</portType>
	<binding name="PartySoapBinding" type="tns:PartyPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
	
		<operation name="CreateParty">
			<soap:operation soapAction="CreateParty" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
		
	</binding>
	<service name="PartyService">
		<port name="PartyPort" binding="tns:PartySoapBinding">
			<soap:address location="TODO" />
		</port>
	</service>
</definitions>