//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.29 at 07:22:13 AM IST 
//


package com.openappengine.salesorder.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SalesHdr" type="{http://openappengine.com/salesorder/types}SalesHdr"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "salesHdr"
})
@XmlRootElement(name = "CreateSalesOrderRequest")
public class CreateSalesOrderRequest {
	
    @XmlElement(name = "SalesHdr", required = true)
    protected SalesHdr salesHdr;

    /**
     * Gets the value of the salesHdr property.
     * 
     * @return
     *     possible object is
     *     {@link SalesHdr }
     *     
     */
    public SalesHdr getSalesHdr() {
        return salesHdr;
    }

    /**
     * Sets the value of the salesHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesHdr }
     *     
     */
    public void setSalesHdr(SalesHdr value) {
        this.salesHdr = value;
    }

}
